#name: Deploy infrastructure (IaC)
#
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v3    
#       - name: Set up dotnet
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '8'
#       - name: Build Solution
#         run: dotnet build src/services/MenuMaker/MenuMaker.sln