// <auto-generated />
using System;
using MenuMaker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuMaker.Infrastructure.Migrations
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20231102190110_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandardUnit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Groceries", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.GroceryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroceryCategories", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("GroceryId")
                        .HasColumnType("integer");

                    b.Property<string>("PartOfDish")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroceryId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.NutritionFacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroceryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroceryId")
                        .IsUnique();

                    b.ToTable("NutritionFacts");
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImgPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Portions")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.Grocery", b =>
                {
                    b.HasOne("MenuMaker.Domain.Models.Recipes.GroceryCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.Ingredient", b =>
                {
                    b.HasOne("MenuMaker.Domain.Models.Recipes.Grocery", "Grocery")
                        .WithMany()
                        .HasForeignKey("GroceryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuMaker.Domain.Models.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grocery");
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.NutritionFacts", b =>
                {
                    b.HasOne("MenuMaker.Domain.Models.Recipes.Grocery", null)
                        .WithOne("NutritionFacts")
                        .HasForeignKey("MenuMaker.Domain.Models.Recipes.NutritionFacts", "GroceryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MenuMaker.Domain.Models.Recipes.ValueObjects.UnitValue", "Calories", b1 =>
                        {
                            b1.Property<int>("NutritionFactsId")
                                .HasColumnType("integer");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NutritionFactsId");

                            b1.ToTable("NutritionFacts");

                            b1.WithOwner()
                                .HasForeignKey("NutritionFactsId");
                        });

                    b.OwnsOne("MenuMaker.Domain.Models.Recipes.ValueObjects.UnitValue", "Carbonhydrates", b1 =>
                        {
                            b1.Property<int>("NutritionFactsId")
                                .HasColumnType("integer");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NutritionFactsId");

                            b1.ToTable("NutritionFacts");

                            b1.WithOwner()
                                .HasForeignKey("NutritionFactsId");
                        });

                    b.OwnsOne("MenuMaker.Domain.Models.Recipes.ValueObjects.UnitValue", "Fat", b1 =>
                        {
                            b1.Property<int>("NutritionFactsId")
                                .HasColumnType("integer");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NutritionFactsId");

                            b1.ToTable("NutritionFacts");

                            b1.WithOwner()
                                .HasForeignKey("NutritionFactsId");
                        });

                    b.OwnsOne("MenuMaker.Domain.Models.Recipes.ValueObjects.UnitValue", "Protein", b1 =>
                        {
                            b1.Property<int>("NutritionFactsId")
                                .HasColumnType("integer");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NutritionFactsId");

                            b1.ToTable("NutritionFacts");

                            b1.WithOwner()
                                .HasForeignKey("NutritionFactsId");
                        });

                    b.OwnsOne("MenuMaker.Domain.Models.Recipes.ValueObjects.UnitValue", "ServingSize", b1 =>
                        {
                            b1.Property<int>("NutritionFactsId")
                                .HasColumnType("integer");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NutritionFactsId");

                            b1.ToTable("NutritionFacts");

                            b1.WithOwner()
                                .HasForeignKey("NutritionFactsId");
                        });

                    b.OwnsOne("MenuMaker.Domain.Models.Recipes.ValueObjects.UnitValue", "Sugar", b1 =>
                        {
                            b1.Property<int>("NutritionFactsId")
                                .HasColumnType("integer");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NutritionFactsId");

                            b1.ToTable("NutritionFacts");

                            b1.WithOwner()
                                .HasForeignKey("NutritionFactsId");
                        });

                    b.Navigation("Calories")
                        .IsRequired();

                    b.Navigation("Carbonhydrates")
                        .IsRequired();

                    b.Navigation("Fat")
                        .IsRequired();

                    b.Navigation("Protein")
                        .IsRequired();

                    b.Navigation("ServingSize")
                        .IsRequired();

                    b.Navigation("Sugar")
                        .IsRequired();
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.Grocery", b =>
                {
                    b.Navigation("NutritionFacts");
                });

            modelBuilder.Entity("MenuMaker.Domain.Models.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
