// <auto-generated />
using System;
using MenuMaker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuMaker.Infrastructure.Migrations
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20250123173830_guid-ids")]
    partial class guidids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.Grocery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasNutritionValues")
                        .HasColumnType("boolean");

                    b.Property<string>("NamePlural")
                        .HasColumnType("text");

                    b.Property<string>("NameSelectable")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NameSingular")
                        .HasColumnType("text");

                    b.Property<string>("StandardUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("g");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NameSelectable")
                        .IsUnique();

                    b.ToTable("Groceries", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.GroceryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("GroceryCategories", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GroceryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartOfDish")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroceryId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImgPath")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Portions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("TimeInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.Grocery", b =>
                {
                    b.HasOne("MenuMaker.Infrastructure.Entities.Recipes.GroceryCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("MenuMaker.Infrastructure.Entities.Recipes.NutritionFacts", "NutritionFacts", b1 =>
                        {
                            b1.Property<Guid>("GroceryId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("NF_Calories");

                            b1.Property<double>("GrammsCarbonhydrates")
                                .HasColumnType("double precision")
                                .HasColumnName("NF_GrammsCarbonhydrates");

                            b1.Property<double>("GrammsFat")
                                .HasColumnType("double precision")
                                .HasColumnName("NF_GrammsFat");

                            b1.Property<double>("GrammsFiber")
                                .HasColumnType("double precision")
                                .HasColumnName("NF_GrammsFiber");

                            b1.Property<double>("GrammsProtein")
                                .HasColumnType("double precision")
                                .HasColumnName("NF_GrammsProtein");

                            b1.Property<double>("GrammsSugar")
                                .HasColumnType("double precision")
                                .HasColumnName("NF_GrammsSugar");

                            b1.HasKey("GroceryId");

                            b1.ToTable("Groceries");

                            b1.WithOwner()
                                .HasForeignKey("GroceryId");

                            b1.OwnsOne("MenuMaker.Domain.Models.ValueObjects.UnitValue", "ServingSize", b2 =>
                                {
                                    b2.Property<Guid>("NutritionFactsGroceryId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Amount")
                                        .HasColumnType("double precision")
                                        .HasColumnName("NF_Serving_Amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("text")
                                        .HasDefaultValue("g")
                                        .HasColumnName("NF_Serving_Unit");

                                    b2.HasKey("NutritionFactsGroceryId");

                                    b2.ToTable("Groceries");

                                    b2.WithOwner()
                                        .HasForeignKey("NutritionFactsGroceryId");
                                });

                            b1.Navigation("ServingSize")
                                .IsRequired();
                        });

                    b.Navigation("Category");

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.GroceryCategory", b =>
                {
                    b.HasOne("MenuMaker.Infrastructure.Entities.Recipes.GroceryCategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.Ingredient", b =>
                {
                    b.HasOne("MenuMaker.Infrastructure.Entities.Recipes.Grocery", "Grocery")
                        .WithMany()
                        .HasForeignKey("GroceryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuMaker.Infrastructure.Entities.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grocery");
                });

            modelBuilder.Entity("MenuMaker.Infrastructure.Entities.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
