name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Get changed files for frontend
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files_yaml: |
            frontend:
              - src/frontend/**
      - name: Build And Deploy
        if: steps.changed-files.outputs.frontend_any_changed == 'true' || github.event_name == 'workflow_dispatch'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_STONE_00D486503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/src/frontend/menumaker-spa" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/menumaker-spa/browser" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
