name: Deploy infrastructure (IaC)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:

      # Checkout repo
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }}

      # Deploy Bicep file
    - name: Resource group ${{ vars.AZ_MM_RG }}
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZ_MM_RG }}
        template: src/infra/azure/rg.bicep
        #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false