name: Deploy infrastructure (IaC)

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:

      # Checkout repo
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }}

      # Deploy Bicep files
    - name: PostgreSQL
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZ_MM_RG }}
        template: src/infra/azure/menumaker/postgresql-db.bicep
        parameters: 'administratorLogin=${{ secrets.SQL_DB_LOGIN }} postgresqlAdminPassword=${{ secrets.SQL_DB_PASSWORD }}'
        failOnStdErr: false

    - name: MenuMakerAppService
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZ_MM_RG }}
        template: src/infra/azure/menumaker/mm-webapp.bicep
        parameters: 'subscriptionId=${{ secrets.AZ_SUBSCRIPTION_ID }} resourceGroupName=${{ secrets.AZ_MM_RG }}'
        failOnStdErr: false